# Generated by Django 5.2 on 2025-05-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('doctor_id', models.IntegerField()),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocID', models.IntegerField()),
                ('DocWeekday', models.CharField(max_length=20)),
                ('DocAvailabilityID', models.IntegerField()),
                ('Timeslot1', models.CharField(max_length=50)),
                ('Timeslot2', models.CharField(max_length=50)),
                ('Timeslot3', models.CharField(max_length=50)),
            ],
        ),
    ]
